name: Document Conversion

on:
  push:
    branches: [ main ]
    paths:
      - '**/src/**'  # Only trigger when files in src directories change
  workflow_dispatch:  # Allow manual triggering

jobs:
  convert:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history for potential branch operations

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc

    - name: Install poppler-utils
      run: sudo apt-get install -y poppler-utils

    - name: Run conversion script
      run: |
        node convert-2.js

    - name: Configure Git
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"

    - name: Commit changes
      run: |
        git add **/md-automated/**
        git add index.md
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-convert documents to markdown" && git push)
